//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaoDeQueijo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int Id { get; set; }
        public int FirstUser { get; set; }
        public int SecondUser { get; set; }
        public bool Accepted { get; set; }
    }
}
